### PR TITLE
Added Automotive Cyber Security Summit

### PR DESCRIPTION
**Pull request by EmilLuta**
Added the Automotive Cyber Security website to the list of presentations available (although it is not a presentation in itself, it has useful data and presentations/ information may be taken from the website).

Furthermore, if you feel the info is not relevant for that topic, a new topic may be added for the 'Conferences'.

### CODE REVIEW

**Comment by jaredmichaelsmith** [comment]
We can add this if we make a new section for conferences, how does that sound? Do you want to take the lead on that?

**Comment by EmilLuta** [comment]
Sounds good. I will get my hands into that. Expect an update by tomorrow!

**Comment by jaredmichaelsmith** [comment]
I merged another pull request which now conflicts with this one, so be sure to address that when you push your changes. :) Thanks again! Let me know if I can help at all.

**Comment by EmilLuta** [comment]
@jaredmichaelsmith It should be up and running. Sorry for the huge waiting time!

**Comment by jaredmichaelsmith** [comment]
Thanks so much! It looks great! Merged.

**Comment by joh1234** [comment]
Thanks so much!
https://goo.gl/JBljdR

**Pull request merged**
